### ISSUE TITLE
element.mask is not a function

### ISSUE THREAD

**Issue by pocesar** [angular-ui/angular-ui-OLDREPO#543]
Can't use the `ui-mask` directive. It doesn't seem to work with jQuery 1.9.1, since I had to remove the `$.browser` since jQuery doesn't have it anymore. 

Another thing, why the input NEEDs a ng-model, why can't I just use it in the form with `ui-mask` without an `ng-model`, I just want to mask the input, don't want Angular to deal with it as being a model on my scope.

**Comment by pocesar** [comment]
I'm now using the new mask module separately, and it works. But I'm wondering, how to use the array "complex" mask instead of the string? I want to permit phones (99) 99999-9999 and (99) 9999-9999 only if the number in () is 11, like (11), is it possible?

And it doesn't seem to support variable length of masks? or optional characters (like masked input plugin)?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?

**Comment by pocesar** [comment]
it doesn't happen on the latest code, but it's missing some functionalities from the jquery-masked plugin, like optional partes of the mask and mask groups

**Comment by ProLoser** [comment]
@pocesar if that's the case can you open relevant ones on that project?
